

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_compose_app_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_compose_app_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_compose_app_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("audio_visualizer")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 29
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_compose_app_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_compose_app_checksum_func_set_onnx_model_path() != 39257:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_func_test() != 17085:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_audiocapturer_end() != 37682:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_audiocapturer_get_notes() != 49622:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_audiocapturer_play() != 42010:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_audiocapturer_reset() != 18590:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_constructor_audiocapturer_new() != 19810:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_capturercallback_on_error() != 29895:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_capturercallback_on_complete() != 34469:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_errorcallback_on_error() != 44615:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_compose_app_checksum_method_errorcallback_on_complete() != 31703:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UNIFFI_CALLBACK_INTERFACE_CAPTURER_CALLBACK_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_CAPTURER_CALLBACK_METHOD1 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_ERROR_CALLBACK_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UNIFFI_CALLBACK_INTERFACE_ERROR_CALLBACK_METHOD1 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
class _UniffiVTableCallbackInterfaceCapturerCallback(ctypes.Structure):
    _fields_ = [
        ("on_error", _UNIFFI_CALLBACK_INTERFACE_CAPTURER_CALLBACK_METHOD0),
        ("on_complete", _UNIFFI_CALLBACK_INTERFACE_CAPTURER_CALLBACK_METHOD1),
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE),
    ]
class _UniffiVTableCallbackInterfaceErrorCallback(ctypes.Structure):
    _fields_ = [
        ("on_error", _UNIFFI_CALLBACK_INTERFACE_ERROR_CALLBACK_METHOD0),
        ("on_complete", _UNIFFI_CALLBACK_INTERFACE_ERROR_CALLBACK_METHOD1),
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE),
    ]
_UniffiLib.uniffi_compose_app_fn_clone_audiocapturer.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_clone_audiocapturer.restype = ctypes.c_void_p
_UniffiLib.uniffi_compose_app_fn_free_audiocapturer.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_free_audiocapturer.restype = None
_UniffiLib.uniffi_compose_app_fn_constructor_audiocapturer_new.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_constructor_audiocapturer_new.restype = ctypes.c_void_p
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_end.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_end.restype = None
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_get_notes.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_get_notes.restype = _UniffiRustBuffer
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_play.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_play.restype = None
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_reset.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_reset.restype = None
_UniffiLib.uniffi_compose_app_fn_init_callback_vtable_capturercallback.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceCapturerCallback),
)
_UniffiLib.uniffi_compose_app_fn_init_callback_vtable_capturercallback.restype = None
_UniffiLib.uniffi_compose_app_fn_init_callback_vtable_errorcallback.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceErrorCallback),
)
_UniffiLib.uniffi_compose_app_fn_init_callback_vtable_errorcallback.restype = None
_UniffiLib.uniffi_compose_app_fn_func_set_onnx_model_path.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_func_set_onnx_model_path.restype = None
_UniffiLib.uniffi_compose_app_fn_func_test.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_compose_app_fn_func_test.restype = _UniffiRustBuffer
_UniffiLib.ffi_compose_app_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_compose_app_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_compose_app_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rustbuffer_free.restype = None
_UniffiLib.ffi_compose_app_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_compose_app_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_u8.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_u8.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_compose_app_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_i8.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_i8.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_compose_app_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_u16.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_u16.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_compose_app_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_i16.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_i16.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_compose_app_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_u32.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_u32.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_compose_app_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_i32.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_i32.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_compose_app_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_u64.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_u64.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_compose_app_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_i64.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_i64.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_compose_app_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_f32.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_f32.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_compose_app_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_f64.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_f64.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_compose_app_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_pointer.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_compose_app_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_compose_app_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_poll_void.restype = None
_UniffiLib.ffi_compose_app_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_cancel_void.restype = None
_UniffiLib.ffi_compose_app_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_compose_app_rust_future_free_void.restype = None
_UniffiLib.ffi_compose_app_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_compose_app_rust_future_complete_void.restype = None
_UniffiLib.uniffi_compose_app_checksum_func_set_onnx_model_path.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_func_set_onnx_model_path.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_func_test.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_func_test.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_end.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_end.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_get_notes.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_get_notes.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_play.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_play.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_reset.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_audiocapturer_reset.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_constructor_audiocapturer_new.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_constructor_audiocapturer_new.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_capturercallback_on_error.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_capturercallback_on_error.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_capturercallback_on_complete.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_capturercallback_on_complete.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_errorcallback_on_error.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_errorcallback_on_error.restype = ctypes.c_uint16
_UniffiLib.uniffi_compose_app_checksum_method_errorcallback_on_complete.argtypes = (
)
_UniffiLib.uniffi_compose_app_checksum_method_errorcallback_on_complete.restype = ctypes.c_uint16
_UniffiLib.ffi_compose_app_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_compose_app_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.
# Magic number for the Rust proxy to call using the same mechanism as every other method,
# to free the callback once it's dropped by Rust.
_UNIFFI_IDX_CALLBACK_FREE = 0
# Return codes for callback calls
_UNIFFI_CALLBACK_SUCCESS = 0
_UNIFFI_CALLBACK_ERROR = 1
_UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

class _UniffiCallbackInterfaceFfiConverter:
    _handle_map = _UniffiHandleMap()

    @classmethod
    def lift(cls, handle):
        return cls._handle_map.get(handle)

    @classmethod
    def read(cls, buf):
        handle = buf.read_u64()
        cls.lift(handle)

    @classmethod
    def check_lower(cls, cb):
        pass

    @classmethod
    def lower(cls, cb):
        handle = cls._handle_map.insert(cb)
        return handle

    @classmethod
    def write(cls, cb, buf):
        buf.write_u64(cls.lower(cb))

class _UniffiConverterUInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u8"
    VALUE_MIN = 0
    VALUE_MAX = 2**8

    @staticmethod
    def read(buf):
        return buf.read_u8()

    @staticmethod
    def write(value, buf):
        buf.write_u8(value)

class _UniffiConverterInt8(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "i8"
    VALUE_MIN = -2**7
    VALUE_MAX = 2**7

    @staticmethod
    def read(buf):
        return buf.read_i8()

    @staticmethod
    def write(value, buf):
        buf.write_i8(value)

class _UniffiConverterUInt64(_UniffiConverterPrimitiveInt):
    CLASS_NAME = "u64"
    VALUE_MIN = 0
    VALUE_MAX = 2**64

    @staticmethod
    def read(buf):
        return buf.read_u64()

    @staticmethod
    def write(value, buf):
        buf.write_u64(value)

class _UniffiConverterFloat(_UniffiConverterPrimitiveFloat):
    @staticmethod
    def read(buf):
        return buf.read_float()

    @staticmethod
    def write(value, buf):
        buf.write_float(value)

class _UniffiConverterBool:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()




class Card:
    title: "str"
    value: "str"
    description: "str"
    card_type: "CardType"
    def __init__(self, *, title: "str", value: "str", description: "str", card_type: "CardType"):
        self.title = title
        self.value = value
        self.description = description
        self.card_type = card_type

    def __str__(self):
        return "Card(title={}, value={}, description={}, card_type={})".format(self.title, self.value, self.description, self.card_type)

    def __eq__(self, other):
        if self.title != other.title:
            return False
        if self.value != other.value:
            return False
        if self.description != other.description:
            return False
        if self.card_type != other.card_type:
            return False
        return True

class _UniffiConverterTypeCard(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return Card(
            title=_UniffiConverterString.read(buf),
            value=_UniffiConverterString.read(buf),
            description=_UniffiConverterString.read(buf),
            card_type=_UniffiConverterTypeCardType.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterString.check_lower(value.title)
        _UniffiConverterString.check_lower(value.value)
        _UniffiConverterString.check_lower(value.description)
        _UniffiConverterTypeCardType.check_lower(value.card_type)

    @staticmethod
    def write(value, buf):
        _UniffiConverterString.write(value.title, buf)
        _UniffiConverterString.write(value.value, buf)
        _UniffiConverterString.write(value.description, buf)
        _UniffiConverterTypeCardType.write(value.card_type, buf)


class EndNote:
    """
    Represents a finalized, fully evaluated musical note emitted upon release or restrike.

    Contains pedagogical performance metrics including sustained pitch stability,
    articulation classifications, attack velocity slope, keybed impact, and spectral timbre.

    # Fields & Values:
    * `pitch: Pitch` — Musical pitch class of the performed note. Range: `Pitch` enum variants.
    * `octave: Octave` — Musical octave register of the performed note. Range: `Octave` enum variants.
    * `tonality_offset: i8` — Initial attack intonation deviation in cents. Range: `-50` to `+50` cents.
    * `avg_cents_offset: i8` — Average intonation deviation in cents across all sustained active frames. Range: `-50` to `+50` cents.
    * `loudness_dbfs: f32` — Peak sustained volume/energy reached during the note envelope. Range: `-120.0` to `0.0` dBFS.
    * `peak_sones: Option<f32>` — Peak sustained perceived loudness in Sones (None for MPM path).
    * `peak_phons: Option<f32>` — Peak sustained perceived loudness level in Phons (None for MPM path).
    * `avg_sones: Option<f32>` — Average sustained perceived loudness in Sones (None for MPM path).
    * `avg_phons: Option<f32>` — Average sustained perceived loudness level in Phons (None for MPM path).
    * `rise_duration: f32` — Duration in seconds from onset strike to peak loudness (attack phase). Range: `0.005` to `2.0+` seconds. IGNORE FOR PIANO
    * `attack_slope: f32` — Initial attack velocity steepness in dBFS per second. Range: `0.0` to `1000.0+` dBFS/s.
    * `note_duration: f32` — Total sounded note duration in seconds from initial strike to release. Range: `> 0.0` seconds.
    * `note_striked: u128` — Timestamp in epoch milliseconds when note onset originally occurred. Range: `>= 0` ms.
    * `articulation: NoteArticulation` — Pedagogical articulation classification (Normal, Staccato, Tenuto, Legato, Marcato). Range: `NoteArticulation` enum variants.
    * `is_mashed: bool` — Flag indicating whether the key was struck excessively hard with low-end thump impact. Range: `true` / `false`.
    * `is_flat: bool` — Flag indicating whether the sustained pitch average was below the instrument's flat intonation threshold. Range: `true` / `false`.
    * `spectral_centroid: f32` — Average spectral center-of-mass in Hertz (spectral brightness / timbral richness). Range: `0.0` to `Nyquist (SampleRate / 2)` Hz.
    * `mpm_clarity: Option<f32>` — McLeod Pitch Method normalized square difference (NSDF) periodicity confidence. Range: `Some(0.0..=1.0)` or `None`.
    * `velocity: u8` — Calibrated MIDI strike velocity. Range: `1` to `127`.
    * `dynamic: DynamicLevel` — Standard musical dynamic marking (ppp to fff).
    * `damping: DampingProfile` — Damping state upon release (DryDamped, PedalSustained, HalfPedal).
    """

    pitch: "Pitch"
    octave: "Octave"
    tonality_offset: "int"
    avg_cents_offset: "int"
    loudness_dbfs: "float"
    peak_sones: "typing.Optional[float]"
    peak_phons: "typing.Optional[float]"
    avg_sones: "typing.Optional[float]"
    avg_phons: "typing.Optional[float]"
    rise_duration: "float"
    attack_slope: "float"
    note_duration: "float"
    note_striked: "U128"
    articulation: "NoteArticulation"
    is_mashed: "bool"
    is_flat: "bool"
    spectral_centroid: "float"
    mpm_clarity: "typing.Optional[float]"
    velocity: "int"
    dynamic: "DynamicLevel"
    damping: "DampingProfile"
    def __init__(self, *, pitch: "Pitch", octave: "Octave", tonality_offset: "int", avg_cents_offset: "int", loudness_dbfs: "float", peak_sones: "typing.Optional[float]", peak_phons: "typing.Optional[float]", avg_sones: "typing.Optional[float]", avg_phons: "typing.Optional[float]", rise_duration: "float", attack_slope: "float", note_duration: "float", note_striked: "U128", articulation: "NoteArticulation", is_mashed: "bool", is_flat: "bool", spectral_centroid: "float", mpm_clarity: "typing.Optional[float]", velocity: "int", dynamic: "DynamicLevel", damping: "DampingProfile"):
        self.pitch = pitch
        self.octave = octave
        self.tonality_offset = tonality_offset
        self.avg_cents_offset = avg_cents_offset
        self.loudness_dbfs = loudness_dbfs
        self.peak_sones = peak_sones
        self.peak_phons = peak_phons
        self.avg_sones = avg_sones
        self.avg_phons = avg_phons
        self.rise_duration = rise_duration
        self.attack_slope = attack_slope
        self.note_duration = note_duration
        self.note_striked = note_striked
        self.articulation = articulation
        self.is_mashed = is_mashed
        self.is_flat = is_flat
        self.spectral_centroid = spectral_centroid
        self.mpm_clarity = mpm_clarity
        self.velocity = velocity
        self.dynamic = dynamic
        self.damping = damping

    def __str__(self):
        return "EndNote(pitch={}, octave={}, tonality_offset={}, avg_cents_offset={}, loudness_dbfs={}, peak_sones={}, peak_phons={}, avg_sones={}, avg_phons={}, rise_duration={}, attack_slope={}, note_duration={}, note_striked={}, articulation={}, is_mashed={}, is_flat={}, spectral_centroid={}, mpm_clarity={}, velocity={}, dynamic={}, damping={})".format(self.pitch, self.octave, self.tonality_offset, self.avg_cents_offset, self.loudness_dbfs, self.peak_sones, self.peak_phons, self.avg_sones, self.avg_phons, self.rise_duration, self.attack_slope, self.note_duration, self.note_striked, self.articulation, self.is_mashed, self.is_flat, self.spectral_centroid, self.mpm_clarity, self.velocity, self.dynamic, self.damping)

    def __eq__(self, other):
        if self.pitch != other.pitch:
            return False
        if self.octave != other.octave:
            return False
        if self.tonality_offset != other.tonality_offset:
            return False
        if self.avg_cents_offset != other.avg_cents_offset:
            return False
        if self.loudness_dbfs != other.loudness_dbfs:
            return False
        if self.peak_sones != other.peak_sones:
            return False
        if self.peak_phons != other.peak_phons:
            return False
        if self.avg_sones != other.avg_sones:
            return False
        if self.avg_phons != other.avg_phons:
            return False
        if self.rise_duration != other.rise_duration:
            return False
        if self.attack_slope != other.attack_slope:
            return False
        if self.note_duration != other.note_duration:
            return False
        if self.note_striked != other.note_striked:
            return False
        if self.articulation != other.articulation:
            return False
        if self.is_mashed != other.is_mashed:
            return False
        if self.is_flat != other.is_flat:
            return False
        if self.spectral_centroid != other.spectral_centroid:
            return False
        if self.mpm_clarity != other.mpm_clarity:
            return False
        if self.velocity != other.velocity:
            return False
        if self.dynamic != other.dynamic:
            return False
        if self.damping != other.damping:
            return False
        return True

class _UniffiConverterTypeEndNote(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return EndNote(
            pitch=_UniffiConverterTypePitch.read(buf),
            octave=_UniffiConverterTypeOctave.read(buf),
            tonality_offset=_UniffiConverterInt8.read(buf),
            avg_cents_offset=_UniffiConverterInt8.read(buf),
            loudness_dbfs=_UniffiConverterFloat.read(buf),
            peak_sones=_UniffiConverterOptionalFloat.read(buf),
            peak_phons=_UniffiConverterOptionalFloat.read(buf),
            avg_sones=_UniffiConverterOptionalFloat.read(buf),
            avg_phons=_UniffiConverterOptionalFloat.read(buf),
            rise_duration=_UniffiConverterFloat.read(buf),
            attack_slope=_UniffiConverterFloat.read(buf),
            note_duration=_UniffiConverterFloat.read(buf),
            note_striked=_UniffiConverterTypeU128.read(buf),
            articulation=_UniffiConverterTypeNoteArticulation.read(buf),
            is_mashed=_UniffiConverterBool.read(buf),
            is_flat=_UniffiConverterBool.read(buf),
            spectral_centroid=_UniffiConverterFloat.read(buf),
            mpm_clarity=_UniffiConverterOptionalFloat.read(buf),
            velocity=_UniffiConverterUInt8.read(buf),
            dynamic=_UniffiConverterTypeDynamicLevel.read(buf),
            damping=_UniffiConverterTypeDampingProfile.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterTypePitch.check_lower(value.pitch)
        _UniffiConverterTypeOctave.check_lower(value.octave)
        _UniffiConverterInt8.check_lower(value.tonality_offset)
        _UniffiConverterInt8.check_lower(value.avg_cents_offset)
        _UniffiConverterFloat.check_lower(value.loudness_dbfs)
        _UniffiConverterOptionalFloat.check_lower(value.peak_sones)
        _UniffiConverterOptionalFloat.check_lower(value.peak_phons)
        _UniffiConverterOptionalFloat.check_lower(value.avg_sones)
        _UniffiConverterOptionalFloat.check_lower(value.avg_phons)
        _UniffiConverterFloat.check_lower(value.rise_duration)
        _UniffiConverterFloat.check_lower(value.attack_slope)
        _UniffiConverterFloat.check_lower(value.note_duration)
        _UniffiConverterTypeU128.check_lower(value.note_striked)
        _UniffiConverterTypeNoteArticulation.check_lower(value.articulation)
        _UniffiConverterBool.check_lower(value.is_mashed)
        _UniffiConverterBool.check_lower(value.is_flat)
        _UniffiConverterFloat.check_lower(value.spectral_centroid)
        _UniffiConverterOptionalFloat.check_lower(value.mpm_clarity)
        _UniffiConverterUInt8.check_lower(value.velocity)
        _UniffiConverterTypeDynamicLevel.check_lower(value.dynamic)
        _UniffiConverterTypeDampingProfile.check_lower(value.damping)

    @staticmethod
    def write(value, buf):
        _UniffiConverterTypePitch.write(value.pitch, buf)
        _UniffiConverterTypeOctave.write(value.octave, buf)
        _UniffiConverterInt8.write(value.tonality_offset, buf)
        _UniffiConverterInt8.write(value.avg_cents_offset, buf)
        _UniffiConverterFloat.write(value.loudness_dbfs, buf)
        _UniffiConverterOptionalFloat.write(value.peak_sones, buf)
        _UniffiConverterOptionalFloat.write(value.peak_phons, buf)
        _UniffiConverterOptionalFloat.write(value.avg_sones, buf)
        _UniffiConverterOptionalFloat.write(value.avg_phons, buf)
        _UniffiConverterFloat.write(value.rise_duration, buf)
        _UniffiConverterFloat.write(value.attack_slope, buf)
        _UniffiConverterFloat.write(value.note_duration, buf)
        _UniffiConverterTypeU128.write(value.note_striked, buf)
        _UniffiConverterTypeNoteArticulation.write(value.articulation, buf)
        _UniffiConverterBool.write(value.is_mashed, buf)
        _UniffiConverterBool.write(value.is_flat, buf)
        _UniffiConverterFloat.write(value.spectral_centroid, buf)
        _UniffiConverterOptionalFloat.write(value.mpm_clarity, buf)
        _UniffiConverterUInt8.write(value.velocity, buf)
        _UniffiConverterTypeDynamicLevel.write(value.dynamic, buf)
        _UniffiConverterTypeDampingProfile.write(value.damping, buf)


class StartNote:
    """
    Represents the onset strike of a musical note in the real-time DSP/Neural pipeline.

    Emitted as soon as the note attack envelope transitions from `Idle` to `Rise`.

    # Fields & Values:
    * `pitch: Pitch` — Musical pitch class (e.g. C, CsDf, D... B, or None). Range: `Pitch` enum variants.
    * `octave: Octave` — Scientific pitch notation octave register (O_1 to O10, or OutOfRange). Range: `Octave` enum variants.
    * `tonality_offset: i8` — Initial intonation deviation in cents relative to equal temperament (A4 = 440 Hz). Range: `-50` to `+50` cents.
    * `loudness_dbfs: f32` — Attack/onset root-mean-square loudness in decibels relative to full scale. Range: `-120.0` to `0.0` dBFS.
    * Perceived linear attack loudness in Sones (None for monophonic MPM path)
    * Perceived linear attack loudness in Phons (None for monophonic MPM path)
    * `note_striked: u128` — Timestamp in epoch milliseconds when the initial note onset occurred. Range: `>= 0` ms.
    * `crest_factor: f32` — Ratio of peak amplitude to RMS energy in dB at attack (transient percussiveness). Range: `0.0` to `30.0+` dB.
    * `sub_thump_dbfs: f32` — Low-frequency energy (20–80 Hz) at strike time for keybed collision detection. Range: `-120.0` to `0.0` dBFS.
    * `mpm_clarity: Option<f32>` — McLeod Pitch Method normalized square difference (NSDF) periodicity confidence at onset. Range: `Some(0.0..=1.0)` (monophonic path) or `None` (polyphonic / uncalculated).
    * `velocity: u8` — Calibrated MIDI strike velocity. Range: `1` to `127`.
    * `dynamic: DynamicLevel` — Standard musical dynamic marking (ppp to fff).
    """

    pitch: "Pitch"
    octave: "Octave"
    tonality_offset: "int"
    loudness_dbfs: "float"
    sones: "typing.Optional[float]"
    phons: "typing.Optional[float]"
    note_striked: "U128"
    crest_factor: "float"
    sub_thump_dbfs: "float"
    mpm_clarity: "typing.Optional[float]"
    velocity: "int"
    dynamic: "DynamicLevel"
    def __init__(self, *, pitch: "Pitch", octave: "Octave", tonality_offset: "int", loudness_dbfs: "float", sones: "typing.Optional[float]", phons: "typing.Optional[float]", note_striked: "U128", crest_factor: "float", sub_thump_dbfs: "float", mpm_clarity: "typing.Optional[float]", velocity: "int", dynamic: "DynamicLevel"):
        self.pitch = pitch
        self.octave = octave
        self.tonality_offset = tonality_offset
        self.loudness_dbfs = loudness_dbfs
        self.sones = sones
        self.phons = phons
        self.note_striked = note_striked
        self.crest_factor = crest_factor
        self.sub_thump_dbfs = sub_thump_dbfs
        self.mpm_clarity = mpm_clarity
        self.velocity = velocity
        self.dynamic = dynamic

    def __str__(self):
        return "StartNote(pitch={}, octave={}, tonality_offset={}, loudness_dbfs={}, sones={}, phons={}, note_striked={}, crest_factor={}, sub_thump_dbfs={}, mpm_clarity={}, velocity={}, dynamic={})".format(self.pitch, self.octave, self.tonality_offset, self.loudness_dbfs, self.sones, self.phons, self.note_striked, self.crest_factor, self.sub_thump_dbfs, self.mpm_clarity, self.velocity, self.dynamic)

    def __eq__(self, other):
        if self.pitch != other.pitch:
            return False
        if self.octave != other.octave:
            return False
        if self.tonality_offset != other.tonality_offset:
            return False
        if self.loudness_dbfs != other.loudness_dbfs:
            return False
        if self.sones != other.sones:
            return False
        if self.phons != other.phons:
            return False
        if self.note_striked != other.note_striked:
            return False
        if self.crest_factor != other.crest_factor:
            return False
        if self.sub_thump_dbfs != other.sub_thump_dbfs:
            return False
        if self.mpm_clarity != other.mpm_clarity:
            return False
        if self.velocity != other.velocity:
            return False
        if self.dynamic != other.dynamic:
            return False
        return True

class _UniffiConverterTypeStartNote(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        return StartNote(
            pitch=_UniffiConverterTypePitch.read(buf),
            octave=_UniffiConverterTypeOctave.read(buf),
            tonality_offset=_UniffiConverterInt8.read(buf),
            loudness_dbfs=_UniffiConverterFloat.read(buf),
            sones=_UniffiConverterOptionalFloat.read(buf),
            phons=_UniffiConverterOptionalFloat.read(buf),
            note_striked=_UniffiConverterTypeU128.read(buf),
            crest_factor=_UniffiConverterFloat.read(buf),
            sub_thump_dbfs=_UniffiConverterFloat.read(buf),
            mpm_clarity=_UniffiConverterOptionalFloat.read(buf),
            velocity=_UniffiConverterUInt8.read(buf),
            dynamic=_UniffiConverterTypeDynamicLevel.read(buf),
        )

    @staticmethod
    def check_lower(value):
        _UniffiConverterTypePitch.check_lower(value.pitch)
        _UniffiConverterTypeOctave.check_lower(value.octave)
        _UniffiConverterInt8.check_lower(value.tonality_offset)
        _UniffiConverterFloat.check_lower(value.loudness_dbfs)
        _UniffiConverterOptionalFloat.check_lower(value.sones)
        _UniffiConverterOptionalFloat.check_lower(value.phons)
        _UniffiConverterTypeU128.check_lower(value.note_striked)
        _UniffiConverterFloat.check_lower(value.crest_factor)
        _UniffiConverterFloat.check_lower(value.sub_thump_dbfs)
        _UniffiConverterOptionalFloat.check_lower(value.mpm_clarity)
        _UniffiConverterUInt8.check_lower(value.velocity)
        _UniffiConverterTypeDynamicLevel.check_lower(value.dynamic)

    @staticmethod
    def write(value, buf):
        _UniffiConverterTypePitch.write(value.pitch, buf)
        _UniffiConverterTypeOctave.write(value.octave, buf)
        _UniffiConverterInt8.write(value.tonality_offset, buf)
        _UniffiConverterFloat.write(value.loudness_dbfs, buf)
        _UniffiConverterOptionalFloat.write(value.sones, buf)
        _UniffiConverterOptionalFloat.write(value.phons, buf)
        _UniffiConverterTypeU128.write(value.note_striked, buf)
        _UniffiConverterFloat.write(value.crest_factor, buf)
        _UniffiConverterFloat.write(value.sub_thump_dbfs, buf)
        _UniffiConverterOptionalFloat.write(value.mpm_clarity, buf)
        _UniffiConverterUInt8.write(value.velocity, buf)
        _UniffiConverterTypeDynamicLevel.write(value.dynamic, buf)





class AudioEngineError:
    def __init__(self):
        raise RuntimeError("AudioEngineError cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    class STREAM_BUILD_ERROR:
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __str__(self):
            return f"AudioEngineError.STREAM_BUILD_ERROR{self._values!r}"

        def __eq__(self, other):
            if not other.is_STREAM_BUILD_ERROR():
                return False
            return self._values == other._values
    class BUFFER_OVERFILL:

        def __init__(self,):
            pass

        def __str__(self):
            return "AudioEngineError.BUFFER_OVERFILL()".format()

        def __eq__(self, other):
            if not other.is_BUFFER_OVERFILL():
                return False
            return True
    
    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_STREAM_BUILD_ERROR(self) -> bool:
        return isinstance(self, AudioEngineError.STREAM_BUILD_ERROR)
    def is_stream_build_error(self) -> bool:
        return isinstance(self, AudioEngineError.STREAM_BUILD_ERROR)
    def is_BUFFER_OVERFILL(self) -> bool:
        return isinstance(self, AudioEngineError.BUFFER_OVERFILL)
    def is_buffer_overfill(self) -> bool:
        return isinstance(self, AudioEngineError.BUFFER_OVERFILL)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
AudioEngineError.STREAM_BUILD_ERROR = type("AudioEngineError.STREAM_BUILD_ERROR", (AudioEngineError.STREAM_BUILD_ERROR, AudioEngineError,), {})  # type: ignore
AudioEngineError.BUFFER_OVERFILL = type("AudioEngineError.BUFFER_OVERFILL", (AudioEngineError.BUFFER_OVERFILL, AudioEngineError,), {})  # type: ignore




class _UniffiConverterTypeAudioEngineError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return AudioEngineError.STREAM_BUILD_ERROR(
                _UniffiConverterString.read(buf),
            )
        if variant == 2:
            return AudioEngineError.BUFFER_OVERFILL(
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_STREAM_BUILD_ERROR():
            _UniffiConverterString.check_lower(value._values[0])
            return
        if value.is_BUFFER_OVERFILL():
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_STREAM_BUILD_ERROR():
            buf.write_i32(1)
            _UniffiConverterString.write(value._values[0], buf)
        if value.is_BUFFER_OVERFILL():
            buf.write_i32(2)







class CardType(enum.Enum):
    IMPORTANT = 0
    
    TIP = 1
    
    FEEDBACK = 2
    


class _UniffiConverterTypeCardType(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return CardType.IMPORTANT
        if variant == 2:
            return CardType.TIP
        if variant == 3:
            return CardType.FEEDBACK
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == CardType.IMPORTANT:
            return
        if value == CardType.TIP:
            return
        if value == CardType.FEEDBACK:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == CardType.IMPORTANT:
            buf.write_i32(1)
        if value == CardType.TIP:
            buf.write_i32(2)
        if value == CardType.FEEDBACK:
            buf.write_i32(3)







class DampingProfile(enum.Enum):
    """
    Damping profile upon note release (staccato key release vs. pedaled sustain).
    """

    DRY_DAMPED = 0
    
    PEDAL_SUSTAINED = 1
    
    HALF_PEDAL = 2
    


class _UniffiConverterTypeDampingProfile(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return DampingProfile.DRY_DAMPED
        if variant == 2:
            return DampingProfile.PEDAL_SUSTAINED
        if variant == 3:
            return DampingProfile.HALF_PEDAL
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == DampingProfile.DRY_DAMPED:
            return
        if value == DampingProfile.PEDAL_SUSTAINED:
            return
        if value == DampingProfile.HALF_PEDAL:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == DampingProfile.DRY_DAMPED:
            buf.write_i32(1)
        if value == DampingProfile.PEDAL_SUSTAINED:
            buf.write_i32(2)
        if value == DampingProfile.HALF_PEDAL:
            buf.write_i32(3)







class DynamicLevel(enum.Enum):
    """
    Dynamic classification level based on acoustic decibels relative to full scale or perceived loudness level in Phons.
    """

    PIANISSISSIMO = 0
    
    PIANISSIMO = 1
    
    PIANO = 2
    
    MEZZO_PIANO = 3
    
    MEZZO_FORTE = 4
    
    FORTE = 5
    
    FORTISSIMO = 6
    
    FORTISSISSIMO = 7
    


class _UniffiConverterTypeDynamicLevel(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return DynamicLevel.PIANISSISSIMO
        if variant == 2:
            return DynamicLevel.PIANISSIMO
        if variant == 3:
            return DynamicLevel.PIANO
        if variant == 4:
            return DynamicLevel.MEZZO_PIANO
        if variant == 5:
            return DynamicLevel.MEZZO_FORTE
        if variant == 6:
            return DynamicLevel.FORTE
        if variant == 7:
            return DynamicLevel.FORTISSIMO
        if variant == 8:
            return DynamicLevel.FORTISSISSIMO
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == DynamicLevel.PIANISSISSIMO:
            return
        if value == DynamicLevel.PIANISSIMO:
            return
        if value == DynamicLevel.PIANO:
            return
        if value == DynamicLevel.MEZZO_PIANO:
            return
        if value == DynamicLevel.MEZZO_FORTE:
            return
        if value == DynamicLevel.FORTE:
            return
        if value == DynamicLevel.FORTISSIMO:
            return
        if value == DynamicLevel.FORTISSISSIMO:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == DynamicLevel.PIANISSISSIMO:
            buf.write_i32(1)
        if value == DynamicLevel.PIANISSIMO:
            buf.write_i32(2)
        if value == DynamicLevel.PIANO:
            buf.write_i32(3)
        if value == DynamicLevel.MEZZO_PIANO:
            buf.write_i32(4)
        if value == DynamicLevel.MEZZO_FORTE:
            buf.write_i32(5)
        if value == DynamicLevel.FORTE:
            buf.write_i32(6)
        if value == DynamicLevel.FORTISSIMO:
            buf.write_i32(7)
        if value == DynamicLevel.FORTISSISSIMO:
            buf.write_i32(8)







class NoteArticulation(enum.Enum):
    NORMAL = 0
    
    STACCATO = 1
    
    TENUTO = 2
    
    LEGATO = 3
    
    MARCATO = 4
    


class _UniffiConverterTypeNoteArticulation(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return NoteArticulation.NORMAL
        if variant == 2:
            return NoteArticulation.STACCATO
        if variant == 3:
            return NoteArticulation.TENUTO
        if variant == 4:
            return NoteArticulation.LEGATO
        if variant == 5:
            return NoteArticulation.MARCATO
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == NoteArticulation.NORMAL:
            return
        if value == NoteArticulation.STACCATO:
            return
        if value == NoteArticulation.TENUTO:
            return
        if value == NoteArticulation.LEGATO:
            return
        if value == NoteArticulation.MARCATO:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == NoteArticulation.NORMAL:
            buf.write_i32(1)
        if value == NoteArticulation.STACCATO:
            buf.write_i32(2)
        if value == NoteArticulation.TENUTO:
            buf.write_i32(3)
        if value == NoteArticulation.LEGATO:
            buf.write_i32(4)
        if value == NoteArticulation.MARCATO:
            buf.write_i32(5)







class Notes:
    def __init__(self):
        raise RuntimeError("Notes cannot be instantiated directly")

    # Each enum variant is a nested class of the enum itself.
    class START:
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __str__(self):
            return f"Notes.START{self._values!r}"

        def __eq__(self, other):
            if not other.is_START():
                return False
            return self._values == other._values
    class END:
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __str__(self):
            return f"Notes.END{self._values!r}"

        def __eq__(self, other):
            if not other.is_END():
                return False
            return self._values == other._values
    

    # For each variant, we have `is_NAME` and `is_name` methods for easily checking
    # whether an instance is that variant.
    def is_START(self) -> bool:
        return isinstance(self, Notes.START)
    def is_start(self) -> bool:
        return isinstance(self, Notes.START)
    def is_END(self) -> bool:
        return isinstance(self, Notes.END)
    def is_end(self) -> bool:
        return isinstance(self, Notes.END)
    

# Now, a little trick - we make each nested variant class be a subclass of the main
# enum class, so that method calls and instance checks etc will work intuitively.
# We might be able to do this a little more neatly with a metaclass, but this'll do.
Notes.START = type("Notes.START", (Notes.START, Notes,), {})  # type: ignore
Notes.END = type("Notes.END", (Notes.END, Notes,), {})  # type: ignore




class _UniffiConverterTypeNotes(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Notes.START(
                _UniffiConverterTypeStartNote.read(buf),
            )
        if variant == 2:
            return Notes.END(
                _UniffiConverterTypeEndNote.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value.is_START():
            _UniffiConverterTypeStartNote.check_lower(value._values[0])
            return
        if value.is_END():
            _UniffiConverterTypeEndNote.check_lower(value._values[0])
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value.is_START():
            buf.write_i32(1)
            _UniffiConverterTypeStartNote.write(value._values[0], buf)
        if value.is_END():
            buf.write_i32(2)
            _UniffiConverterTypeEndNote.write(value._values[0], buf)







class Octave(enum.Enum):
    OUT_OF_RANGE = 0
    
    O_1 = 1
    
    O0 = 2
    
    O1 = 3
    
    O2 = 4
    
    O3 = 5
    
    O4 = 6
    
    O5 = 7
    
    O6 = 8
    
    O7 = 9
    
    O8 = 10
    
    O9 = 11
    
    O10 = 12
    


class _UniffiConverterTypeOctave(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Octave.OUT_OF_RANGE
        if variant == 2:
            return Octave.O_1
        if variant == 3:
            return Octave.O0
        if variant == 4:
            return Octave.O1
        if variant == 5:
            return Octave.O2
        if variant == 6:
            return Octave.O3
        if variant == 7:
            return Octave.O4
        if variant == 8:
            return Octave.O5
        if variant == 9:
            return Octave.O6
        if variant == 10:
            return Octave.O7
        if variant == 11:
            return Octave.O8
        if variant == 12:
            return Octave.O9
        if variant == 13:
            return Octave.O10
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Octave.OUT_OF_RANGE:
            return
        if value == Octave.O_1:
            return
        if value == Octave.O0:
            return
        if value == Octave.O1:
            return
        if value == Octave.O2:
            return
        if value == Octave.O3:
            return
        if value == Octave.O4:
            return
        if value == Octave.O5:
            return
        if value == Octave.O6:
            return
        if value == Octave.O7:
            return
        if value == Octave.O8:
            return
        if value == Octave.O9:
            return
        if value == Octave.O10:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Octave.OUT_OF_RANGE:
            buf.write_i32(1)
        if value == Octave.O_1:
            buf.write_i32(2)
        if value == Octave.O0:
            buf.write_i32(3)
        if value == Octave.O1:
            buf.write_i32(4)
        if value == Octave.O2:
            buf.write_i32(5)
        if value == Octave.O3:
            buf.write_i32(6)
        if value == Octave.O4:
            buf.write_i32(7)
        if value == Octave.O5:
            buf.write_i32(8)
        if value == Octave.O6:
            buf.write_i32(9)
        if value == Octave.O7:
            buf.write_i32(10)
        if value == Octave.O8:
            buf.write_i32(11)
        if value == Octave.O9:
            buf.write_i32(12)
        if value == Octave.O10:
            buf.write_i32(13)







class Pitch(enum.Enum):
    NONE = 0
    
    C = 1
    
    CS_DF = 2
    
    D = 3
    
    DS_EF = 4
    
    E = 5
    
    F = 6
    
    FS_GF = 7
    
    G = 8
    
    GS_AF = 9
    
    A = 10
    
    AS_BF = 11
    
    B = 12
    


class _UniffiConverterTypePitch(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return Pitch.NONE
        if variant == 2:
            return Pitch.C
        if variant == 3:
            return Pitch.CS_DF
        if variant == 4:
            return Pitch.D
        if variant == 5:
            return Pitch.DS_EF
        if variant == 6:
            return Pitch.E
        if variant == 7:
            return Pitch.F
        if variant == 8:
            return Pitch.FS_GF
        if variant == 9:
            return Pitch.G
        if variant == 10:
            return Pitch.GS_AF
        if variant == 11:
            return Pitch.A
        if variant == 12:
            return Pitch.AS_BF
        if variant == 13:
            return Pitch.B
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if value == Pitch.NONE:
            return
        if value == Pitch.C:
            return
        if value == Pitch.CS_DF:
            return
        if value == Pitch.D:
            return
        if value == Pitch.DS_EF:
            return
        if value == Pitch.E:
            return
        if value == Pitch.F:
            return
        if value == Pitch.FS_GF:
            return
        if value == Pitch.G:
            return
        if value == Pitch.GS_AF:
            return
        if value == Pitch.A:
            return
        if value == Pitch.AS_BF:
            return
        if value == Pitch.B:
            return
        raise ValueError(value)

    @staticmethod
    def write(value, buf):
        if value == Pitch.NONE:
            buf.write_i32(1)
        if value == Pitch.C:
            buf.write_i32(2)
        if value == Pitch.CS_DF:
            buf.write_i32(3)
        if value == Pitch.D:
            buf.write_i32(4)
        if value == Pitch.DS_EF:
            buf.write_i32(5)
        if value == Pitch.E:
            buf.write_i32(6)
        if value == Pitch.F:
            buf.write_i32(7)
        if value == Pitch.FS_GF:
            buf.write_i32(8)
        if value == Pitch.G:
            buf.write_i32(9)
        if value == Pitch.GS_AF:
            buf.write_i32(10)
        if value == Pitch.A:
            buf.write_i32(11)
        if value == Pitch.AS_BF:
            buf.write_i32(12)
        if value == Pitch.B:
            buf.write_i32(13)




# RustError
# We want to define each variant as a nested class that's also a subclass,
# which is tricky in Python.  To accomplish this we're going to create each
# class separately, then manually add the child classes to the base class's
# __dict__.  All of this happens in dummy class to avoid polluting the module
# namespace.
class RustError(Exception):
    pass

_UniffiTempRustError = RustError

class RustError:  # type: ignore
    class AudioEngineError(_UniffiTempRustError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], AudioEngineError):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'AudioEngineError', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "RustError.AudioEngineError({})".format(str(self))
    _UniffiTempRustError.AudioEngineError = AudioEngineError # type: ignore
    class NotImplementedError(_UniffiTempRustError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "RustError.NotImplementedError({})".format(str(self))
    _UniffiTempRustError.NotImplementedError = NotImplementedError # type: ignore
    class FeatureExtactorBuildError(_UniffiTempRustError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "RustError.FeatureExtactorBuildError({})".format(str(self))
    _UniffiTempRustError.FeatureExtactorBuildError = FeatureExtactorBuildError # type: ignore
    class Custom(_UniffiTempRustError):
        def __init__(self, *values):
            if len(values) != 1:
                raise TypeError(f"Expected 1 arguments, found {len(values)}")
            if not isinstance(values[0], str):
                raise TypeError(f"unexpected type for tuple element 0 - expected 'str', got '{type(values[0])}'")
            super().__init__(", ".join(map(repr, values)))
            self._values = values

        def __getitem__(self, index):
            return self._values[index]

        def __repr__(self):
            return "RustError.Custom({})".format(str(self))
    _UniffiTempRustError.Custom = Custom # type: ignore

RustError = _UniffiTempRustError # type: ignore
del _UniffiTempRustError


class _UniffiConverterTypeRustError(_UniffiConverterRustBuffer):
    @staticmethod
    def read(buf):
        variant = buf.read_i32()
        if variant == 1:
            return RustError.AudioEngineError(
                _UniffiConverterTypeAudioEngineError.read(buf),
            )
        if variant == 2:
            return RustError.NotImplementedError(
                _UniffiConverterString.read(buf),
            )
        if variant == 3:
            return RustError.FeatureExtactorBuildError(
                _UniffiConverterString.read(buf),
            )
        if variant == 4:
            return RustError.Custom(
                _UniffiConverterString.read(buf),
            )
        raise InternalError("Raw enum value doesn't match any cases")

    @staticmethod
    def check_lower(value):
        if isinstance(value, RustError.AudioEngineError):
            _UniffiConverterTypeAudioEngineError.check_lower(value._values[0])
            return
        if isinstance(value, RustError.NotImplementedError):
            _UniffiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, RustError.FeatureExtactorBuildError):
            _UniffiConverterString.check_lower(value._values[0])
            return
        if isinstance(value, RustError.Custom):
            _UniffiConverterString.check_lower(value._values[0])
            return

    @staticmethod
    def write(value, buf):
        if isinstance(value, RustError.AudioEngineError):
            buf.write_i32(1)
            _UniffiConverterTypeAudioEngineError.write(value._values[0], buf)
        if isinstance(value, RustError.NotImplementedError):
            buf.write_i32(2)
            _UniffiConverterString.write(value._values[0], buf)
        if isinstance(value, RustError.FeatureExtactorBuildError):
            buf.write_i32(3)
            _UniffiConverterString.write(value._values[0], buf)
        if isinstance(value, RustError.Custom):
            buf.write_i32(4)
            _UniffiConverterString.write(value._values[0], buf)




class CapturerCallback(typing.Protocol):
    def on_error(self, msg: "str"):
        raise NotImplementedError
    def on_complete(self, ):
        raise NotImplementedError


# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplCapturerCallback:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_CAPTURER_CALLBACK_METHOD0
    def on_error(
            uniffi_handle,
            msg,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeCapturerCallback._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterString.lift(msg), )
            method = uniffi_obj.on_error
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_CAPTURER_CALLBACK_METHOD1
    def on_complete(
            uniffi_handle,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeCapturerCallback._handle_map.get(uniffi_handle)
        def make_call():
            args = ()
            method = uniffi_obj.on_complete
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_FREE
    def _uniffi_free(uniffi_handle):
        _UniffiConverterTypeCapturerCallback._handle_map.remove(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceCapturerCallback(
        on_error,
        on_complete,
        _uniffi_free
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_compose_app_fn_init_callback_vtable_capturercallback(ctypes.byref(_uniffi_vtable))

# The _UniffiConverter which transforms the Callbacks in to Handles to pass to Rust.
_UniffiConverterTypeCapturerCallback = _UniffiCallbackInterfaceFfiConverter()




class ErrorCallback(typing.Protocol):
    def on_error(self, msg: "RustError"):
        raise NotImplementedError
    def on_complete(self, ):
        raise NotImplementedError


# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplErrorCallback:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_ERROR_CALLBACK_METHOD0
    def on_error(
            uniffi_handle,
            msg,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeErrorCallback._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterTypeRustError.lift(msg), )
            method = uniffi_obj.on_error
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_ERROR_CALLBACK_METHOD1
    def on_complete(
            uniffi_handle,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeErrorCallback._handle_map.get(uniffi_handle)
        def make_call():
            args = ()
            method = uniffi_obj.on_complete
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_FREE
    def _uniffi_free(uniffi_handle):
        _UniffiConverterTypeErrorCallback._handle_map.remove(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceErrorCallback(
        on_error,
        on_complete,
        _uniffi_free
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_compose_app_fn_init_callback_vtable_errorcallback(ctypes.byref(_uniffi_vtable))

# The _UniffiConverter which transforms the Callbacks in to Handles to pass to Rust.
_UniffiConverterTypeErrorCallback = _UniffiCallbackInterfaceFfiConverter()



class _UniffiConverterOptionalFloat(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterFloat.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterFloat.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterFloat.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterOptionalTypeNotes(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterTypeNotes.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterTypeNotes.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterTypeNotes.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")


class _UniffiConverterTypeU128:
    @staticmethod
    def write(value, buf):
        _UniffiConverterUInt64.write(value, buf)

    @staticmethod
    def read(buf):
        return _UniffiConverterUInt64.read(buf)

    @staticmethod
    def lift(value):
        return _UniffiConverterUInt64.lift(value)

    @staticmethod
    def check_lower(value):
        return _UniffiConverterUInt64.check_lower(value)

    @staticmethod
    def lower(value):
        return _UniffiConverterUInt64.lower(value)

# objects.
class AudioCapturerProtocol(typing.Protocol):
    def end(self, ):
        raise NotImplementedError
    def get_notes(self, ):
        raise NotImplementedError
    def play(self, ):
        raise NotImplementedError
    def reset(self, ):
        raise NotImplementedError
# AudioCapturer is a Rust-only trait - it's a wrapper around a Rust implementation.
class AudioCapturer():
    _pointer: ctypes.c_void_p
    def __init__(self, path: "str",err_cb: "CapturerCallback"):
        _UniffiConverterString.check_lower(path)
        
        _UniffiConverterTypeCapturerCallback.check_lower(err_cb)
        
        self._pointer = _uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_constructor_audiocapturer_new,
        _UniffiConverterString.lower(path),
        _UniffiConverterTypeCapturerCallback.lower(err_cb))

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_free_audiocapturer, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_clone_audiocapturer, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst


    def end(self, ) -> None:
        _uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_end,self._uniffi_clone_pointer(),)






    def get_notes(self, ) -> "typing.Optional[Notes]":
        return _UniffiConverterOptionalTypeNotes.lift(
            _uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_get_notes,self._uniffi_clone_pointer(),)
        )





    def play(self, ) -> None:
        _uniffi_rust_call_with_error(_UniffiConverterTypeRustError,_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_play,self._uniffi_clone_pointer(),)






    def reset(self, ) -> None:
        _uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_method_audiocapturer_reset,self._uniffi_clone_pointer(),)







class _UniffiConverterTypeAudioCapturer:

    @staticmethod
    def lift(value: int):
        return AudioCapturer._make_instance_(value)

    @staticmethod
    def check_lower(value: AudioCapturer):
        if not isinstance(value, AudioCapturer):
            raise TypeError("Expected AudioCapturer instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: AudioCapturerProtocol):
        if not isinstance(value, AudioCapturer):
            raise TypeError("Expected AudioCapturer instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: AudioCapturerProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))
U128 = int

# Async support

def set_onnx_model_path(path: "str") -> None:
    _UniffiConverterString.check_lower(path)
    
    _uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_func_set_onnx_model_path,
        _UniffiConverterString.lower(path))


def test() -> "Card":
    return _UniffiConverterTypeCard.lift(_uniffi_rust_call(_UniffiLib.uniffi_compose_app_fn_func_test,))


__all__ = [
    "InternalError",
    "AudioEngineError",
    "CardType",
    "DampingProfile",
    "DynamicLevel",
    "NoteArticulation",
    "Notes",
    "Octave",
    "Pitch",
    "RustError",
    "Card",
    "EndNote",
    "StartNote",
    "set_onnx_model_path",
    "test",
    "AudioCapturer",
    "CapturerCallback",
    "ErrorCallback",
]

