[package]
name = "compose-app"
version = "0.1.0"
edition = "2024"

[dependencies]
uniffi = "0.29.4"
cpal = "0.18.1"
log = "0.4"
android_logger = "0.13"
hound = "3.5"
ringbuf = "0.4"
pitch-detection = "0.3"
arrayvec = "0.7"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]
path = "src/commonMain/rust/lib.rs"

[[example]]
name = "mic_listener"
path = "rust_examples/mic_listener.rs"


